config/routes.rb
Rails.application.routes.draw do

  resources :nannies
  root             'static_pages#home'
  get 'Hilfe'    => 'static_pages#Hilfe'
  get 'Über'   => 'static_pages#Über'
  get 'Kontakt' => 'static_pages#Kontakt'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'Nannysuche', to: 'static_pages#Nannysuche'
  get 'Nanny-Angebot', to: 'static_pages#Nanny-Angebot'
  get 'Willkommen', to: 'static_pages#Willkommen'


  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :firstname, presence: true, length: {maximum: 25 }
  validates :name, presence: true, length: {maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def Home
  end

  def Hilfe
  end

  def Über
  end

  def Kontakt
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private

  def user_params
    params.require(:user).permit( :firstname, :name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end


  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end


  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer yellowgreen">
  <nav>
    <ul>
      <li><%= link_to "Hilfe",   'Hilfe' %></li>
      <li><%= link_to "Über",    'Über' %></li>
      <li><%= link_to "Kontakt", 'Kontakt' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar yellowgreen">
  <div class="container">
    <%= link_to "Nanny-App", root_path , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Startseite",   root_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Nannysuche",   'Nannysuche' %></li>
            <li><%= link_to "Nanny-Dienst anbieten",   nannies_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Benutzerkonto <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to current_user.firstname, current_user %></li>
                <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Ausloggen", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Einloggen", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/Hilfe.html.erb
<% provide(:title, "Hilfe") %>
<h1>Hilfe</h1>
<p>
  Hier könnte man verschiedene Seiten verlinken. Zum Beispiel "Babysitter suchen" oder "Als Nanny anbieten". <br><br>
  ansonsten noch weitere Informationen geben für die Nutzung der App.<br><br>
  Informationen über das Verfahren und was hier so hinter steckt (für die Kunden)<br><br>
</p>

<br><br><br><br>





____________________________________________________________________________________________________________<br><br>
Sie wollen das Angebot der Babysitter-App nutzen, sind jedoch noch nicht registriert? Dann registrieren sie
sich jetzt <%= link_to "hier!", signup_path %> <br>
Wenn sie schon registriert sind, können sie sich
<%= link_to "hier", login_path %> mit ihren Nutzerdaten einloggen.






<br><br><br><br>
<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>

<br><br><br><br><br><br>



____________________________________________________________________________________________________________<br><br>

KNÖPFE ZUM SELBERBASTELN:<br>
<!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
<button type="button" class="btn btn-primary">Primary</button>

<!-- Secondary, outline button -->
<button type="button" class="btn btn-secondary">Secondary</button>

<!-- Indicates a successful or positive action -->
<button type="button" class="btn btn-success">Success</button>

<!-- Contextual button for informational alert messages -->
<button type="button" class="btn btn-info">Hellau</button>

<!-- Indicates caution should be taken with this action -->
<button type="button" class="btn btn-warning">Warning</button>

<!-- Indicates a dangerous or potentially negative action -->
<button type="button" class="btn btn-danger">Danger</button>

<!-- Deemphasize a button by making it look like a link while maintaining button behavior -->
<button type="button" class="btn btn-link">Link</button>

app/views/static_pages/Kontakt.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Kontakt</h1>
<p>



<div class="center jumbotron">


Bei Nachfragen oder Anregungen wenden sie sich gerne an unseren Kunden-Support.<br><br><br>


  Nanny-App-Support<br>
  nanny@rubyonrails.de<br>
  Königsworter Platz 1<br>
  30167 Hannover<br>



  <br>
  <br>
  <br>

 Seiteninhaber: Louis-Phillip Herrmann & Fiete Pape<br>

</div>


<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>



app/views/static_pages/Nanny-Angebot.html.erb
<% provide(:title, "Nanny-Dienst anbieten") %>
<h1>Nanny-Dienst anbieten</h1>
<p>
  Hier könnte man sie ihre Dienste als Sitter anbieten.


  <%= link_to "Zurück zur Startseite", 'Angebot' %>
</p>





<br><br><br><br>
<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>

app/views/static_pages/Nannysuche.html.erb
<% provide(:title, "Nannysuche") %>
<h1>Nannysuche</h1>

<div class="center jumbotron">

  Hier werden Ihnen 2 verschiedene Möglichkeiten der Suche angeboten. Für zeitlich kurz angebundene Kunden, kann eine
  Schnellsuche durchgeführt werden. Dabei wird einzig auf Grundlage der Zahlungsbereitschaft eine im Budget liegende
  Sitter-Nanny zugeordnet. Auf Wunsch kann natülich auch eine differenzierte Suche erfolgen, in welcher mehrere
  Faktoren ausgewählt werden. Auf dieses Weise können Sie festelgen, welche persönlichen Anforderungen ihr Sitter
  erfüllen soll. <br><br>
  Hier können sie eine geeignete Nanny finden. Dann würde dazu noch ganz viel Text stehen, in dem der Nutzer über
  bestimmte Sachen aufgeklärt wird oder Tipps bekommt. UNd und und.... blabla bla bla bla. Hier können sie eine
  geeignete Nanny finden. Dann würde dazu noch ganz viel Text stehen, in dem der Nutzer über
  bestimmte Sachen aufgeklärt wird oder Tipps bekommt. UNd und und.... blabla bla bla bla.
  Hier können sie eine geeignete Nanny finden. Dann würde dazu noch ganz viel Text stehen, in dem der Nutzer über
  bestimmte Sachen aufgeklärt wird oder Tipps bekommt. UNd und und.... blabla bla bla bla.
  Hier können sie eine geeignete Nanny finden. Dann würde dazu noch ganz viel Text stehen, in dem der Nutzer über
  bestimmte Sachen aufgeklärt wird oder Tipps bekommt. UNd und und.... blabla bla bla bla.
  Hier können sie eine geeignete Nanny finden. Dann würde dazu noch ganz viel Text stehen, in dem der Nutzer über
  bestimmte Sachen aufgeklärt wird oder Tipps bekommt. UNd und und.... blabla bla bla bla.
  Hier können sie eine geeignete Nanny finden. Dann würde dazu noch ganz viel Text stehen, in dem der Nutzer über
  bestimmte Sachen aufgeklärt wird oder Tipps bekommt. UNd und und.... blabla bla bla bla. <br><br><br><br>

<div class="center">
  <%= link_to "Schnellsuche starten", root_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Detaillierte Suche starten", root_path, class: "btn btn-lg btn-primary" %>

</div>
  </div>



<br><br><br><br>
<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>

app/views/static_pages/Startseite.html.erb
<% provide(:title, "Startseite") %>
<% if logged_in? %>



    <h1>Hallo,  <%= current_user.firstname %>! :)</h1>
    <div class="center">
         Was möchtest du als nächstes tun?
         </div>

<br><br><br>

    <div class="linkcontainer">
      <div class="centerwrapper">

        <div class="image">
        <%= link_to image_tag("find-a-babysitter.gif", height: '100', alt: "Rails logo"),'Hilfe' %><br>
        <%= link_to "Eine Nanny suchen", '' %>
      </div>


      <br><br>
      <div class="image">
      <%= link_to image_tag("fcb.png", height: '70', alt: "Rails logo"),'Kontakt' %><br>
      <%= link_to "Kontakt", 'Kontakt' %>
    </div>

    <br><br>
    <div class="image">
    <%= link_to image_tag("Sitter1.jpg", height: '70', alt: "Rails logo"),'Kontakt' %><br>
    <%= link_to "Kontakt", 'Kontakt' %>
    </div>

    <br><br>
    <div class="image">
    <%= link_to image_tag("Sitter2.jpg", height: '80', alt: "Rails logo"),'Kontakt' %><br>
    <%= link_to "Kontakt", 'Kontakt' %>
    </div>
    </div>
    </div>




<% else %>
Hallo



<% end %>

app/views/static_pages/Willkommen.html.erb
<% provide(:title, "Willkommen") %>
<h1>Hallo <%= current_user.name%>, Willkommen der Nanny-App</h1>
<p>


  <br>

  Diese Seite muss aufgerufen werden, wenn jemand erfolgreich eingeloggt wurde bzw. wenn sich jemand erfolgreich
  registriert hat.
</p>



<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="center jumbotron ">
      <h1>Willkommen in der Nanny-App</h1>

      <h2>
        Die  offizielle Online-Nanny-Vermittlung von Feidex und Lauzi :)
      </h2>
      <br>

      <%= link_to image_tag("find-a-babysitter.gif", alt: "Rails logo"),
                  'https://www.google.de' %>
    </div>

<% else %>
    <div class="center jumbotron ">
      <h1>Willkommen in der Nanny-App</h1>

      <h2>
        Die  offizielle Online-Nanny-Vermittlung von Feidex und Lauzi :)
      </h2>
      <br>

      <%= link_to image_tag("find-a-babysitter.gif", alt: "Rails logo"),
                  'https://www.google.de' %>

      <br><br><br><br>

      <%= link_to "REGISTRIERUNG FÜR NEUKUNDEN", signup_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "EINLOGGEN FÜR BESTANDSKUNDEN", login_path, class: "btn btn-lg btn-primary" %>

<% end %>


app/views/static_pages/Über.html.erb
<% provide(:title, "Ueber") %>
<h1>Über</h1><br>

<div class="center jumbotron">

Diese Applikation wurden im Rahmen der Veranstaltung "Entwicklung von Anwendungssystemen" von Louis-Phillip Herrmann
  und Fiete Pape erstellt.



</div>


<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Einstellungen") %>
<h1>Änderung der Einstellungen</h1>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name, "Vorname:" %>
        <%= f.text_field :firstname, class: 'form-control' %>

        <%= f.label :name, "Nachname:" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "E-Mail:" %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password, "Passwort:" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Bestätigung des Passworts:" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
<br>
        <%= f.submit "Änderungen speichern", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

<br><br><br><br>
<%= link_to "Zurück zur Startseite", root_path, class:"btn btn-warning" %>

app/views/users/index.html.erb
<% provide(:title, 'Alle Users') %>
<h1>Alle User</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
      <%= render @users %>
       <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Registrierung') %>
<h1>Registrierung</h1>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name, "Vorname:" %>
        <%= f.text_field :firstname, class: 'form-control' %>

        <%= f.label :name, "Nachname:" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email, "E-Mail:" %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password, "Passwort:" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Bestätigung des Passworts:" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

<br>
        <%= f.submit "Neues Benutzerkonto erstellen", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.firstname %>
        <%= @user.name %> <br>
        <%= @user.email %>

      </h1>
    </section>
  </aside>
</div>